# These setting are overlayed over `default.toml` in unit tests
# to exercise parsing values that are not viable as defaults.

[validator_key]
path = "dummy.sk"
kind = "ethereum"

[ipc]
subnet_id = "/r31415926"

[resolver.membership]
static_subnets = [
  "/r31415926/f2xwzbdu7z5sam6hc57xxwkctciuaz7oe5omipwbq",
]

[resolver.discovery]
static_addresses = [
  "/ip4/198.51.100.0/tcp/4242/p2p/QmYyQSo1c1Ym7orWxLYvCrM2EmxFTANf8wXmmE7DWjhx5N",
  "/ip6/2604:1380:2000:7a00::1/udp/4001/quic/p2p/QmbLHAnMoJPWSCR5Zhtx6BHJX9KiKNN6tpvbUcqanj75Nb",
  "/ip4/192.0.2.0/tcp/5002/p2p/QmdPU7PfRyKehdrP5A3WqmjyD6bhVpU1mLGKppa2FjGDjZ/p2p-circuit/p2p/QmVT6GYwjeeAF5TR485Yc58S3xRF5EFsZ5YAF4VcP3URHt",
]

[resolver.connection]
listen_addr = "/ip4/198.51.100.2/tcp/1234"
external_addresses = [
  "/ip4/198.51.100.2/tcp/1234",
  "/dns4/my.node.com/tcp/1234",
]


[testing]
push_chain_meta = false
