[package]
name = "fendermint_vm_interpreter"
description = "Execute messages using the FVM"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fendermint_vm_actor_interface = { path = "../actor_interface" }
fendermint_vm_core = { path = "../core" }
fendermint_vm_event = { path = "../event" }
fendermint_vm_encoding = { path = "../encoding" }
fendermint_vm_genesis = { path = "../genesis" }
fendermint_vm_message = { path = "../message" }
fendermint_vm_resolver = { path = "../resolver" }
fendermint_vm_topdown = { path = "../topdown" }
fendermint_crypto = { path = "../../crypto" }
fendermint_eth_hardhat = { path = "../../eth/hardhat" }
fendermint_rpc = { path = "../../rpc" }
fendermint_tracing = { path = "../../tracing" }
fendermint_actors = { path = "../../actors" }
fendermint_actor_chainmetadata = { path = "../../actors/chainmetadata" }
fendermint_actor_eam = { workspace = true }
fendermint_testing = { path = "../../testing", optional = true }
ipc_actors_abis = { workspace = true }

ipc-api = { workspace = true }

async-trait = { workspace = true }
async-stm = { workspace = true }
anyhow = { workspace = true }
ethers = { workspace = true }
hex = { workspace = true }
num-traits = { workspace = true }
serde = { workspace = true }
serde_with = { workspace = true }
serde_json = { workspace = true }
tendermint = { workspace = true }
tendermint-rpc = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }

cid = { workspace = true }
fvm = { workspace = true }
fvm_shared = { workspace = true }
fvm_ipld_blockstore = { workspace = true }
fvm_ipld_encoding = { workspace = true }
fvm_ipld_car = { workspace = true }

futures-core = { workspace = true }
futures-util = { workspace = true }
libipld = { workspace = true }
tokio = { workspace = true }
pin-project = { workspace = true }
tokio-stream = { workspace = true }
tokio-util = { workspace = true }

arbitrary = { workspace = true, optional = true }
quickcheck = { workspace = true, optional = true }
rand = { workspace = true, optional = true }

[dev-dependencies]
quickcheck = { workspace = true }
quickcheck_macros = { workspace = true }
tempfile = { workspace = true }

fendermint_vm_interpreter = { path = ".", features = ["arb"] }
fendermint_testing = { path = "../../testing", features = ["golden"] }
fvm = { workspace = true, features = ["arb", "testing"] }
fendermint_vm_genesis = { path = "../genesis", features = ["arb"] }
multihash = { workspace = true }

[features]
default = []
bundle = []
arb = [
    "arbitrary",
    "quickcheck",
    "fvm_shared/arb",
    "fendermint_testing/arb",
    "rand",
]
